### ISSUE TITLE
Can you advice my reproduction result?

### ISSUE THREAD

**Issue by HeegyuKim** [HKUSTDial/NL2SQL360#5]
Hello! Thank you for sharing nice work!

I downloaded your published baseline results and evaluated them using the BIRD code. However, the BIRD benchmark result is different from the paper's.

I have been trying to solve this issue and I have noticed that my BIRD dev database filename is dev_20240627.zip. 
This different database version can be a reason for different reproduction results.

Could you share your dev dataset version?
![스크린샷 2024-08-02 오후 6 52 00](https://github.com/user-attachments/assets/b2eb2a8b-f160-40d1-a8ef-d05a3e448487)

**Comment by BugMaker-Boyan** [comment]
Thank you very much for your interest in our work!

Regarding the issue you raised, I have successfully reproduced and compared the results. The discrepancy is due to a recent update to the Dev dataset by the BIRD team, which means it is not the same version as the one used in our paper.

I have uploaded the BIRD Dev dataset we used in our paper to Google Drive. Here is the link:
[Google Drive](https://drive.google.com/drive/folders/1SDwY30H2r6XNYeS53wcZNocVFm0hVgpz?usp=sharing)

I hope this resolves your issue.

Additionally, we have recently released the NL2SQL360 Package, which provides an easy-to-use, multi-angle solution. Feel free to use it! If you have any other questions, feel free to discuss them with us!
